#!/usr/bin/env bash
set -Eeuo pipefail
# ============================================================
# ANIME CLOUD V4 — ULTRA PRO 3D EDITION
# Pterodactyl • Wings • Docker • Cloudflare • RDP • VS Code
# Created by the mrhacker
# ============================================================
R='\033[0m'; B='\033[1m'; DIM='\033[2m'; C='\033[96m'; CY='\033[36m'; G='\033[92m'; Y='\033[93m'; M='\033[95m'; P='\033[35m'; RED='\033[91m'; W='\033[97m'
BASE=/opt/anime-cloud-v4; LOG="$BASE/install.log"; mkdir -p "$BASE"; touch "$LOG"
trap 'echo -e "${RED}✖ Error on line $LINENO${R}" | tee -a "$LOG"' ERR
ok(){ echo -e "${G}${B}✔${R} $*"; }; warn(){ echo -e "${Y}${B}⚠${R} $*"; }; pause(){ read -rp $'\nPress ENTER to continue... '; }
spin(){ local text="$1" i c; for c in '◐' '◓' '◑' '◒'; do printf "\r${C}${B}%s ${M}%s${R}" "$text" "$c"; sleep .07; done; printf "\r${G}${B}✔ %s${R}\n" "$text"; }
bar(){ local text="$1" i; printf "${C}${B}%s [${R}" "$text"; for i in {1..24}; do printf "${M}█${R}"; sleep .015; done; printf "${C}${B}] 100%%${R}\n"; }
logo(){ clear; echo -e "${C}${B}╔══════════════════════════════════════════════════════════════╗${R}"; echo -e "${C}${B}║${R}                  ${M}✦ A N I M E   C L O U D ✦${R}                 ${C}${B}║${R}"; echo -e "${C}${B}║${R}                    ${B}${W}V4 ULTRA PRO${R}                           ${C}${B}║${R}"; echo -e "${C}${B}╠══════════════════════════════════════════════════════════════╣${R}"; echo -e "${C}${B}║${R}        ${M}◆${R} ${C}PTERODACTYL${R}  ${G}◆${R} ${C}WINGS${R}  ${Y}◆${R} ${C}CLOUDFLARE${R}        ${C}${B}║${R}"; echo -e "${C}${B}║${R}          ${P}3D NEON CONTROL CENTER • AUTOMATION${R}              ${C}${B}║${R}"; echo -e "${C}${B}║${R}                 ${DIM}✦ Created by the mrhacker ✦${R}                ${C}${B}║${R}"; echo -e "${C}${B}╚══════════════════════════════════════════════════════════════╝${R}"; }
sysinfo(){ logo; source /etc/os-release; echo -e "${C}${B}╭────────────── SYSTEM HOLOGRAM ──────────────╮${R}"; printf " ${G}OS${R}            : %s\n" "$PRETTY_NAME"; printf " ${G}Kernel${R}        : %s\n" "$(uname -r)"; printf " ${G}Architecture${R}  : %s\n" "$(uname -m)"; printf " ${G}CPU${R}           : %s cores\n" "$(nproc)"; printf " ${G}RAM${R}           : %s\n" "$(free -h|awk '/Mem:/{print $3" / "$2}')"; printf " ${G}Disk${R}          : %s\n" "$(df -h /|awk 'NR==2{print $3" / "$2" ("$5")"}')"; printf " ${G}Public IPv4${R}   : %s\n" "$(curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo unknown)"; printf " ${G}Virtualization${R}: %s\n" "$(systemd-detect-virt 2>/dev/null || echo unknown)"; echo -e "${C}${B}╰──────────────────────────────────────────────╯${R}"; pause; }
docker_install(){ command -v docker >/dev/null 2>&1 || curl -fsSL https://get.docker.com | sh; systemctl enable --now docker; ok 'Docker ready.'; }
rdp(){ apt-get update -y; apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11; systemctl enable --now xrdp; command -v ufw >/dev/null && ufw allow 3389/tcp || true; ok 'RDP ready on TCP 3389.'; pause; }
vscode(){ docker_install; read -rp 'Container [vscode]: ' n; n=${n:-vscode}; read -rp 'Port [8080]: ' p; p=${p:-8080}; read -rsp 'Password: ' pass; echo; pass=${pass:-123456}; docker rm -f "$n" >/dev/null 2>&1 || true; docker run -d --name "$n" -p "$p:8080" -e PASSWORD="$pass" --restart unless-stopped ghcr.io/coder/code-server:latest; command -v ufw >/dev/null && ufw allow "$p/tcp" || true; ok "VS Code Server: http://SERVER-IP:$p"; pause; }
container_menu(){ while true; do logo; echo -e "${M}${B}╭────────────── 📦 CONTAINER TOOLS ──────────────╮${R}"; echo -e " ${G}[1]${R} 🖥️  RDP"; echo -e " ${G}[2]${R} 💻 VS CODE SERVER"; echo -e " ${RED}[0]${R} ↩ Back"; echo -e "${M}${B}╰────────────────────────────────────────────────╯${R}"; read -rp 'Container > ' x; case "$x" in 1) rdp;;2) vscode;;0)return;;*)warn 'Invalid option';;esac; done; }
vps(){ wget -qO /tmp/anime-cloud-vm-manager.sh https://raw.githubusercontent.com/sureshkumak26-art/vm/main/anime-cloud-vm-manager.sh && chmod +x /tmp/anime-cloud-vm-manager.sh && /tmp/anime-cloud-vm-manager.sh; }
cloudflare(){ echo -e "${C}${B}Cloudflare Tunnel Setup${R}"; command -v cloudflared >/dev/null 2>&1 || { curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | gpg --dearmor -o /usr/share/keyrings/cloudflare-main.gpg; echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' >/etc/apt/sources.list.d/cloudflared.list; apt-get update -y; apt-get install -y cloudflared; }; read -rsp 'Cloudflare Tunnel token: ' token; echo; [[ -n "$token" ]] && cloudflared service install "$token" && systemctl enable --now cloudflared && ok 'Cloudflare Tunnel active.' || warn 'No token supplied.'; pause; }
firewall(){ apt-get install -y ufw; ufw default deny incoming; ufw default allow outgoing; ufw allow 22/tcp; ufw allow 80/tcp; ufw allow 443/tcp; ufw allow 3389/tcp; ufw allow 8080/tcp; ufw --force enable; ok 'Firewall configured.'; pause; }
health(){ logo; echo -e "${C}${B}SERVICE MATRIX${R}"; for s in docker nginx mariadb redis-server xrdp cloudflared; do if systemctl is-active --quiet "$s" 2>/dev/null; then echo -e " ${G}● ONLINE${R}  $s"; else echo -e " ${RED}● OFFLINE${R} $s"; fi; done; echo; docker ps --format 'table {{.Names}}\t{{.Ports}}\t{{.Status}}' 2>/dev/null || true; pause; }
full(){ logo; echo -e "${M}${B}FULL AUTO DEPLOYMENT${R}"; bar 'Preparing system'; apt-get update -y; apt-get install -y curl wget git unzip ca-certificates gnupg nginx mariadb-server redis-server ufw; docker_install; bar 'Core services prepared'; ok 'Base installation complete.'; warn 'Pterodactyl Panel/Wings require domain and node credentials; use their dedicated options or your existing installer for production configuration.'; pause; }
menu(){ while true; do logo; echo -e "${C}${B}╭────────────────── MAIN CONTROL ──────────────────╮${R}"; echo -e " ${G}[1]${R} 🖥️  SYSTEM DETECTION"; echo -e " ${G}[2]${R} 🦎 PTERODACTYL PANEL"; echo -e " ${G}[3]${R} ⚙️  WINGS"; echo -e " ${G}[4]${R} 🐳 DOCKER"; echo -e " ${G}[5]${R} 🗄️  MARIADB + REDIS"; echo -e " ${G}[6]${R} 📊 SYSTEM INFORMATION"; echo -e " ${M}[7]${R} 📦 CONTAINER TOOLS"; echo -e " ${C}[8]${R} ☁️  CLOUDFLARE TUNNEL"; echo -e " ${Y}[9]${R} 🖥️  VPS MANAGER"; echo -e " ${Y}[10]${R} 🔒 SSL"; echo -e " ${Y}[11]${R} 🛡️  FIREWALL"; echo -e " ${Y}[12]${R} ❤️  HEALTH CHECK"; echo -e " ${P}[13]${R} 🚀 FULL AUTO INSTALL"; echo -e " ${RED}[0]${R} ⏻ EXIT"; echo -e "${C}${B}╰──────────────────────────────────────────────────╯${R}"; echo; read -rp 'Anime Cloud V4 > ' x; case "$x" in 1|6) sysinfo;;2) echo 'Use your existing Pterodactyl installer configuration.'; pause;;3) echo 'Use your existing Wings node configuration.'; pause;;4) docker_install; pause;;5) apt-get install -y mariadb-server redis-server; systemctl enable --now mariadb redis-server; pause;;7) container_menu;;8) cloudflare;;9) vps;;10) echo 'SSL: use certbot --nginx -d your-domain'; pause;;11) firewall;;12) health;;13) full;;0) clear;exit 0;;*) warn 'Invalid option'; sleep .6;;esac; done; }
[[ $EUID -eq 0 ]] || { echo 'Run as root.'; exit 1; }; menu
