#!/usr/bin/env bash
set -Eeuo pipefail
# ============================================================
# ANIME CLOUD V4 — ULTRA PRO 3D ANIMATED EDITION
# Animated terminal HUD • Pterodactyl • Wings • Cloudflare
# RDP • VS Code • VPS Manager • Munder Difflin
# Created by the mrhacker
# ============================================================
R='\033[0m'; B='\033[1m'; DIM='\033[2m'; C='\033[96m'; CY='\033[36m'; G='\033[92m'; Y='\033[93m'; M='\033[95m'; P='\033[35m'; RED='\033[91m'; W='\033[97m'; BL='\033[94m'
BASE=/opt/anime-cloud-v4; LOG="$BASE/install.log"; mkdir -p "$BASE"; touch "$LOG"
trap 'echo -e "${RED}✖ ERROR ${R}line $LINENO${R}" | tee -a "$LOG"' ERR
ok(){ echo -e "${G}${B}✔${R} $*"; }; warn(){ echo -e "${Y}${B}⚠${R} $*"; }; pause(){ read -rp $'\nPress ENTER to continue... '; }
progress(){ local title="$1" i; echo -ne "${C}${B}${title}${R} "; for i in {1..28}; do printf "${M}█${R}"; sleep .015; done; echo -e " ${G}100%${R}"; }
boot(){ clear; printf '\033[?25l'; for x in {1..2}; do echo -e "${C}${B}╔══════════════════════════════════════════════════════════════╗${R}"; echo -e "${C}${B}║${R}              ${M}✦ A N I M E   C L O U D ✦${R}                 ${C}${B}║${R}"; echo -e "${C}${B}║${R}                 ${W}${B}V4 ULTRA PRO${R}                             ${C}${B}║${R}"; echo -e "${C}${B}╠══════════════════════════════════════════════════════════════╣${R}"; echo -e "${C}${B}║${R}        ${M}◆${R} ${CY}3D CORE${R}  ${G}◆${R} ${CY}AUTOMATION${R}  ${Y}◆${R} ${CY}CLOUD${R}        ${C}${B}║${R}"; echo -e "${C}${B}║${R}             ${P}NEON TERMINAL CONTROL CENTER${R}                 ${C}${B}║${R}"; echo -e "${C}${B}╚══════════════════════════════════════════════════════════════╝${R}"; sleep .12; done; printf '\033[?25h'; }
logo(){ clear; echo -e "${C}${B}╔══════════════════════════════════════════════════════════════╗${R}"; echo -e "${C}${B}║${R}                 ${M}╱╲  A N I M E  C L O U D  ╱╲${R}             ${C}${B}║${R}"; echo -e "${C}${B}║${R}               ${P}╱████╲  ${W}${B}V4 ULTRA PRO${R}  ${P}╱████╲${R}              ${C}${B}║${R}"; echo -e "${C}${B}║${R}              ${CY}╲████╱  ${M}3D ANIMATED HUD${R}  ${CY}╲████╱${R}             ${C}${B}║${R}"; echo -e "${C}${B}║${R}                    ${DIM}✦ by the mrhacker ✦${R}                  ${C}${B}║${R}"; echo -e "${C}${B}╚══════════════════════════════════════════════════════════════╝${R}"; }
sysinfo(){ logo; source /etc/os-release; echo -e "${M}${B}╭────────────── 3D SYSTEM HOLOGRAM ──────────────╮${R}"; printf " ${G}OS${R}            : %s\n" "$PRETTY_NAME"; printf " ${G}Kernel${R}        : %s\n" "$(uname -r)"; printf " ${G}Architecture${R}  : %s\n" "$(uname -m)"; printf " ${G}CPU${R}           : %s cores\n" "$(nproc)"; printf " ${G}RAM${R}           : %s\n" "$(free -h|awk '/Mem:/{print $3" / "$2}')"; printf " ${G}Disk${R}          : %s\n" "$(df -h /|awk 'NR==2{print $3" / "$2" ("$5")"}')"; printf " ${G}Public IPv4${R}   : %s\n" "$(curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo unknown)"; printf " ${G}Virtualization${R}: %s\n" "$(systemd-detect-virt 2>/dev/null || echo unknown)"; echo -e "${M}${B}╰──────────────────────────────────────────────────╯${R}"; pause; }
docker_install(){ progress 'DOCKER CORE'; command -v docker >/dev/null 2>&1 || curl -fsSL https://get.docker.com | sh; systemctl enable --now docker; ok 'Docker ready.'; }
rdp(){ progress 'RDP DEPLOYMENT'; apt-get update -y; apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11; systemctl enable --now xrdp; command -v ufw >/dev/null && ufw allow 3389/tcp || true; ok 'RDP ready on TCP 3389.'; pause; }
vscode(){ docker_install; read -rp 'Container [vscode]: ' n; n=${n:-vscode}; read -rp 'Port [8080]: ' p; p=${p:-8080}; read -rsp 'Password [123456]: ' pass; echo; pass=${pass:-123456}; docker rm -f "$n" >/dev/null 2>&1 || true; progress 'VS CODE CONTAINER'; docker run -d --name "$n" -p "$p:8080" -e PASSWORD="$pass" --restart unless-stopped ghcr.io/coder/code-server:latest; command -v ufw >/dev/null && ufw allow "$p/tcp" || true; ok "VS Code Server: http://SERVER-IP:$p"; pause; }
container_menu(){ while true; do logo; echo -e "${M}${B}╭────────────── 📦 3D CONTAINER DECK ─────────────╮${R}"; echo -e " ${G}[1]${R} 🖥️  RDP"; echo -e " ${G}[2]${R} 💻 VS CODE SERVER"; echo -e " ${RED}[0]${R} ↩ Back"; echo -e "${M}${B}╰──────────────────────────────────────────────────╯${R}"; read -rp 'Container > ' x; case "$x" in 1) rdp;;2) vscode;;0)return;;*)warn 'Invalid option'; sleep .5;;esac; done; }
vps(){ progress 'VPS MANAGER LINK'; wget -qO /tmp/anime-cloud-vm-manager.sh https://raw.githubusercontent.com/sureshkumak26-art/vm/main/anime-cloud-vm-manager.sh && chmod +x /tmp/anime-cloud-vm-manager.sh && /tmp/anime-cloud-vm-manager.sh; }
munder(){ logo; echo -e "${M}${B}╭──────────── MUNDER DIFFLIN ────────────╮${R}"; echo -e " ${C}Electron development environment${R}"; echo -e " ${DIM}Repository: chaitanyagiri/munder-difflin${R}"; echo -e "${M}${B}╰─────────────────────────────────────────╯${R}"; command -v git >/dev/null 2>&1 || apt-get update -y && apt-get install -y git; command -v npm >/dev/null 2>&1 || { warn 'Node.js/npm is required. Install Node.js 20+ first.'; pause; return; }; if [[ -d munder-difflin/.git ]]; then cd munder-difflin; git pull --ff-only; else git clone https://github.com/chaitanyagiri/munder-difflin.git; cd munder-difflin; fi; progress 'NPM INSTALL'; npm install; ok 'Dependencies installed. node-pty postinstall will rebuild against Electron ABI when supported by the project.'; echo -e "${Y}${B}Starting Electron hot reload...${R}"; npm run dev; }
cloudflare(){ logo; echo -e "${C}${B}☁ CLOUDFLARE TUNNEL${R}"; command -v cloudflared >/dev/null 2>&1 || { curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | gpg --dearmor -o /usr/share/keyrings/cloudflare-main.gpg; echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' >/etc/apt/sources.list.d/cloudflared.list; apt-get update -y; apt-get install -y cloudflared; }; read -rsp 'Cloudflare Tunnel token: ' token; echo; [[ -n "$token" ]] && cloudflared service install "$token" && systemctl enable --now cloudflared && ok 'Cloudflare Tunnel active.' || warn 'No token supplied.'; pause; }
firewall(){ apt-get install -y ufw; ufw default deny incoming; ufw default allow outgoing; ufw allow 22/tcp; ufw allow 80/tcp; ufw allow 443/tcp; ufw allow 3389/tcp; ufw allow 8080/tcp; ufw --force enable; ok 'Firewall configured.'; pause; }
health(){ logo; echo -e "${M}${B}╭────────────── LIVE SERVICE MATRIX ──────────────╮${R}"; for s in docker nginx mariadb redis-server xrdp cloudflared; do if systemctl is-active --quiet "$s" 2>/dev/null; then echo -e " ${G}◆ ONLINE ${R} $s"; else echo -e " ${RED}◇ OFFLINE${R} $s"; fi; done; echo -e "${M}${B}╰──────────────────────────────────────────────────╯${R}"; docker ps --format 'table {{.Names}}\t{{.Ports}}\t{{.Status}}' 2>/dev/null || true; pause; }
full(){ logo; echo -e "${M}${B}🚀 FULL AUTO DEPLOYMENT${R}"; progress 'SYSTEM PREPARATION'; apt-get update -y; apt-get install -y curl wget git unzip ca-certificates gnupg nginx mariadb-server redis-server ufw; docker_install; progress 'CORE SERVICES'; ok 'Base services installed.'; warn 'Pterodactyl Panel/Wings require domain and node credentials; configure them with your production credentials.'; pause; }
menu(){ while true; do logo; echo -e "${C}${B}╭────────────────── 3D MAIN CONTROL ──────────────────╮${R}"; echo -e " ${G}[1]${R} 🖥️  SYSTEM DETECTION"; echo -e " ${G}[2]${R} 🦎 PTERODACTYL PANEL"; echo -e " ${G}[3]${R} ⚙️  WINGS"; echo -e " ${G}[4]${R} 🐳 DOCKER"; echo -e " ${G}[5]${R} 🗄️  MARIADB + REDIS"; echo -e " ${G}[6]${R} 📊 SYSTEM INFORMATION"; echo -e " ${M}[7]${R} 📦 CONTAINER TOOLS"; echo -e " ${C}[8]${R} ☁️  CLOUDFLARE TUNNEL"; echo -e " ${Y}[9]${R} 🖥️  VPS MANAGER"; echo -e " ${Y}[10]${R} 🧰 MUNDER DIFFLIN"; echo -e " ${Y}[11]${R} 🔒 SSL"; echo -e " ${Y}[12]${R} 🛡️  FIREWALL"; echo -e " ${Y}[13]${R} ❤️  HEALTH CHECK"; echo -e " ${P}[14]${R} 🚀 FULL AUTO INSTALL"; echo -e " ${RED}[0]${R} ⏻ EXIT"; echo -e "${C}${B}╰──────────────────────────────────────────────────────╯${R}"; echo; read -rp 'Anime Cloud V4 ▶ ' x; case "$x" in 1|6) sysinfo;;2) warn 'Configure Pterodactyl Panel with your production domain/database credentials.'; pause;;3) warn 'Configure Wings with your Pterodactyl node credentials.'; pause;;4) docker_install; pause;;5) apt-get install -y mariadb-server redis-server; systemctl enable --now mariadb redis-server; pause;;7) container_menu;;8) cloudflare;;9) vps;;10) munder;;11) echo 'SSL: certbot --nginx -d your-domain'; pause;;12) firewall;;13) health;;14) full;;0) printf '\033[?25h'; clear; exit 0;;*) warn 'Invalid option'; sleep .6;;esac; done; }
[[ $EUID -eq 0 ]] || { echo 'Run as root.'; exit 1; }; trap 'printf "\033[?25h"' EXIT; boot; menu
