#!/usr/bin/env bash
set -Eeuo pipefail
# ============================================================
# ANIME CLOUD V4 ULTRA PRO V2 — 3D NEON TERMINAL
# Created by the mrhacker
# ============================================================
R='\033[0m'; B='\033[1m'; C='\033[96m'; G='\033[92m'; Y='\033[93m'; M='\033[95m'; P='\033[35m'; RED='\033[91m'; W='\033[97m'
BASE=/opt/anime-cloud-v4; mkdir -p "$BASE"; LOG="$BASE/install.log"
trap 'printf "\033[?25h"' EXIT INT TERM
ok(){ echo -e "${G}${B}✔${R} $*"; }; warn(){ echo -e "${Y}${B}⚠${R} $*"; }; pause(){ read -rp $'\nPress ENTER... '; }
load(){ echo -ne "${C}${B}$1 ${R}"; for i in {1..18}; do printf "${M}◆${R}"; sleep .02; done; echo -e " ${G}ONLINE${R}"; }
logo(){ clear; echo -e "${C}${B}╔════════════════════════════════════════════════════════════╗${R}"; echo -e "${C}║${R}          ${M}${B}✦  A N I M E   C L O U D  ✦${R}                   ${C}║${R}"; echo -e "${C}║${R}                ${W}${B}3D NEON EDITION V4${R}                    ${C}║${R}"; echo -e "${C}╚════════════════════════════════════════════════════════════╝${R}"; echo -e "${P}${B}       █████╗ ███╗   ██╗██╗███╗   ███╗███████╗${R}"; echo -e "${P}${B}      ██╔══██╗████╗  ██║██║████╗ ████║██╔════╝${R}"; echo -e "${P}${B}      ███████║██╔██╗ ██║██║██╔████╔██║█████╗  ${R}"; echo -e "${P}${B}      ██╔══██║██║╚██╗██║██║██║╚██╔╝██║██╔══╝  ${R}"; echo -e "${P}${B}      ██║  ██║██║ ╚████║██║██║ ╚═╝ ██║███████╗${R}"; echo -e "${P}${B}      ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝     ╚═╝╚══════╝${R}"; echo; echo -e "${C}╭──────────────────────────────────────────────────────────╮${R}"; echo -e "${C}│${R} ☁ PTERODACTYL   ⚙ WINGS   ☁ CLOUDFLARE   🐳 DOCKER     ${C}│${R}"; echo -e "${C}│${R} ✦ NEON UI       ◆ SSL     ◆ FIREWALL      ◆ AUTO       ${C}│${R}"; echo -e "${C}╰──────────────────────────────────────────────────────────╯${R}"; echo -e "${P}3D INTERFACE ◆◆◆◆◆ ${G}ONLINE${R}"; }
sysinfo(){ logo; source /etc/os-release; echo -e "${C}╭─────────────── SYSTEM INFORMATION ───────────────╮${R}"; echo " OS           : $PRETTY_NAME"; echo " Kernel       : $(uname -r)"; echo " Architecture : $(uname -m)"; echo " CPU          : $(nproc) cores"; echo " RAM          : $(free -h|awk '/Mem:/{print $3" / "$2}')"; echo " Disk         : $(df -h /|awk 'NR==2{print $3" / "$2" ("$5")"}')"; echo " IPv4         : $(hostname -I|awk '{print $1}')"; echo " Virt         : $(systemd-detect-virt 2>/dev/null || echo unknown)"; echo -e "${C}╰───────────────────────────────────────────────────╯${R}"; pause; }
docker_install(){ load 'DOCKER INSTALL'; command -v docker >/dev/null 2>&1 || curl -fsSL https://get.docker.com | sh; systemctl enable --now docker; ok 'Docker ready'; pause; }
node_install(){ logo; apt update; apt install -y curl; load 'NVM INSTALL'; curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.6/install.sh | bash; export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; load 'NODE.JS 24'; nvm install 24; nvm alias default 24; nvm use 24; ok "Node $(node -v) / npm $(npm -v)"; pause; }
python_install(){ logo; load 'PYTHON 3 INSTALL'; apt update && apt install -y python3 python-is-python3; ok "Python $(python --version 2>&1)"; pause; }
claude_install(){ logo; load 'CLAUDE CODE INSTALL'; curl -fsSL https://claude.ai/install.sh | bash; ok 'Claude Code installed'; pause; }
munder_install(){ logo; apt update; apt install -y git; if [ -d munder-difflin/.git ]; then cd munder-difflin; git pull --ff-only; else git clone https://github.com/chaitanyagiri/munder-difflin.git; cd munder-difflin; fi; npm install; ok 'Munder Difflin dependencies installed'; npm run dev; }
n8n_install(){ logo; apt update; apt install -y git; if [ -d selfhost-ai/.git ]; then cd selfhost-ai; git pull --ff-only; else git clone https://github.com/kossakovsky/selfhost-ai; cd selfhost-ai; fi; sudo bash ./scripts/install.sh; ok 'Selfhost AI installer completed'; pause; }
container_menu(){ while true; do logo; echo -e "${M}╭──────────── 📦 CONTAINER TOOLS ─────────────╮${R}"; echo -e "${G}[1]${R} 🖥 Linux RDP"; echo -e "${G}[2]${R} 💻 VS Code Server"; echo -e "${G}[3]${R} 📊 Status"; echo -e "${RED}[4]${R} 🛑 Stop VS Code"; echo -e "${RED}[0]${R} ↩ Back"; echo -e "${M}╰──────────────────────────────────────────────╯${R}"; read -rp 'Container ➜ ' c; case "$c" in 1) apt update; apt install -y xrdp xfce4 xfce4-goodies; systemctl enable --now xrdp; ok 'RDP active on 3389'; pause;; 2) docker_install >/dev/null; docker rm -f vscode >/dev/null 2>&1 || true; docker run -d --name vscode -p 8080:8080 -e PASSWORD=123456 --restart unless-stopped ghcr.io/coder/code-server:latest; ok 'VS Code: http://SERVER-IP:8080'; pause;; 3) docker ps; systemctl status xrdp --no-pager 2>/dev/null || true; pause;; 4) docker stop vscode 2>/dev/null || true; ok 'VS Code stopped'; pause;; 0)return;; esac; done; }
cloudflare(){ logo; apt update; apt install -y curl gnupg; if ! command -v cloudflared >/dev/null 2>&1; then curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | gpg --dearmor -o /usr/share/keyrings/cloudflare-main.gpg; echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' >/etc/apt/sources.list.d/cloudflared.list; apt update; apt install -y cloudflared; fi; read -rsp 'Cloudflare Tunnel token: ' t; echo; [ -n "$t" ] && cloudflared service install "$t" && systemctl enable --now cloudflared && ok 'Tunnel active'; pause; }
firewall(){ apt install -y ufw; ufw default deny incoming; ufw default allow outgoing; ufw allow 22/tcp; ufw allow 80/tcp; ufw allow 443/tcp; ufw allow 3389/tcp; ufw allow 8080/tcp; ufw --force enable; ok 'Firewall configured'; pause; }
ddos_protection(){ logo; echo -e "${C}${B}🛡 DDoS PROTECTION / DIAGNOSTICS${R}"; echo; echo 'Active connections:'; ss -Htan | wc -l; echo; echo 'Top remote IPs:'; ss -Htan | awk '{print $5}' | sed 's/:[0-9]*$//' | sort | uniq -c | sort -nr | head -10; echo; echo 'Listening ports:'; ss -lntup | head -20; echo; warn 'No traffic-flooding/attack tool is installed.'; pause; }
health(){ logo; for s in docker nginx mariadb redis-server xrdp cloudflared; do systemctl is-active --quiet "$s" 2>/dev/null && echo -e "${G}◆ ONLINE${R} $s" || echo -e "${RED}◇ OFFLINE${R} $s"; done; pause; }
full(){ logo; load 'SYSTEM PREPARATION'; apt update; apt install -y curl wget git unzip ca-certificates gnupg nginx mariadb-server redis-server ufw; docker_install; ok 'Base stack installed'; pause; }
main(){ while true; do logo; echo -e "${C}╭──────────── 🚀 DEPLOYMENT & SERVICES ─────────────╮${R}"; echo -e "${G}[1]${R} 🚀 FULL AUTO INSTALL"; echo -e "${G}[2]${R} 🖥 VPS / SYSTEM INFORMATION"; echo -e "${G}[3]${R} ⚙ Wings Auto Setup"; echo -e "${G}[4]${R} 🦎 Pterodactyl Panel"; echo -e "${G}[5]${R} 🐳 Docker"; echo -e "${G}[6]${R} 📊 Service Monitor"; echo -e "${G}[7]${R} 📦 Container Tools"; echo -e "${C}╰───────────────────────────────────────────────────╯${R}"; echo; echo -e "${P}╭──────────── ☁ CLOUD & SECURITY ─────────────────╮${R}"; echo -e "${G}[8]${R} ☁ Cloudflare Tunnel"; echo -e "${G}[9]${R} 🌐 Cloudflare DNS"; echo -e "${G}[10]${R} 🔒 Let's Encrypt SSL"; echo -e "${G}[11]${R} 🛡 Firewall"; echo -e "${G}[12]${R} 🔍 Health Check"; echo -e "${G}[13]${R} 🛡 DDoS Protection / Diagnostics"; echo -e "${P}╰──────────────────────────────────────────────────╯${R}"; echo; echo -e "${C}╭──────────────────── ✨ TOOLS ─────────────────────╮${R}"; echo -e "${G}[14]${R} 🟢 Node.js 24"; echo -e "${G}[15]${R} 🐍 Python 3"; echo -e "${G}[16]${R} 🤖 Claude Code"; echo -e "${G}[17]${R} 🧰 Munder Difflin"; echo -e "${G}[18]${R} 🧠 N8N / Selfhost AI"; echo -e "${G}[19]${R} 🖥 VPS Manager"; echo -e "${RED}[0]${R} EXIT"; echo -e "${C}╰───────────────────────────────────────────────────╯${R}"; read -rp $'\n╭─[ Anime Cloud 3D ]─➜ ' x; case "$x" in 1)full;;2)sysinfo;;3)warn 'Wings setup requires Pterodactyl node configuration.'; pause;;4)warn 'Panel setup requires production domain/database credentials.'; pause;;5)docker_install;;6)systemctl --failed; pause;;7)container_menu;;8)cloudflare;;9)warn 'Configure DNS records in your Cloudflare zone.'; pause;;10)warn 'Use certbot --nginx -d your-domain after DNS is ready.'; pause;;11)firewall;;12)health;;13)ddos_protection;;14)node_install;;15)python_install;;16)claude_install;;17)munder_install;;18)n8n_install;;19)wget -qO /tmp/anime-cloud-vm-manager.sh https://raw.githubusercontent.com/sureshkumak26-art/vm/main/anime-cloud-vm-manager.sh && chmod +x /tmp/anime-cloud-vm-manager.sh && /tmp/anime-cloud-vm-manager.sh;;0)clear; exit 0;;*)warn 'Invalid option'; sleep .6;;esac; done; }
[ "$EUID" -eq 0 ] || { echo 'Run as root.'; exit 1; }
main
