#!/usr/bin/env bash
set -Eeuo pipefail
R='\033[0m'; C='\033[96m'; G='\033[92m'; Y='\033[93m'; M='\033[95m'; RED='\033[91m'; B='\033[1m'
ok(){ echo -e "${G}✔${R} $*"; }; warn(){ echo -e "${Y}⚠${R} $*"; }; pause(){ read -rp 'Press ENTER to continue...'; }
install_rdp(){ apt-get update -y; apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11; systemctl enable --now xrdp; command -v ufw >/dev/null && ufw allow 3389/tcp || true; ok 'Linux RDP installed on port 3389.'; }
rdp_docker(){ command -v docker >/dev/null 2>&1 || { warn 'Docker is required.'; return; }; read -rp 'Container name [anime-rdp]: ' NAME; NAME=${NAME:-anime-rdp}; read -rp 'Host port [3389]: ' PORT; PORT=${PORT:-3389}; docker rm -f "$NAME" >/dev/null 2>&1 || true; docker run -d --name "$NAME" --restart unless-stopped -p "${PORT}:3389" dorowu/ubuntu-desktop-lxde-vnc:latest; command -v ufw >/dev/null && ufw allow "${PORT}/tcp" || true; ok "RDP container started: $NAME:$PORT"; }
vscode(){ command -v docker >/dev/null 2>&1 || { warn 'Docker is required.'; return; }; read -rp 'Container name [vscode]: ' NAME; NAME=${NAME:-vscode}; read -rp 'Host port [8080]: ' PORT; PORT=${PORT:-8080}; read -rsp 'VS Code password [123456]: ' PASS; echo; PASS=${PASS:-123456}; docker rm -f "$NAME" >/dev/null 2>&1 || true; docker run -d --name "$NAME" -p "${PORT}:8080" -e PASSWORD="$PASS" --restart unless-stopped ghcr.io/coder/code-server:latest; command -v ufw >/dev/null && ufw allow "${PORT}/tcp" || true; ok "VS Code Server: http://SERVER-IP:${PORT}"; }
status(){ echo -e "${C}${B}Docker containers:${R}"; docker ps --format 'table {{.Names}}\t{{.Ports}}\t{{.Status}}' 2>/dev/null || true; systemctl is-active --quiet xrdp && ok 'xrdp RUNNING' || warn 'xrdp STOPPED'; }
stop_rdp(){ systemctl disable --now xrdp 2>/dev/null || true; docker ps --format '{{.Names}}' 2>/dev/null | grep -E 'anime-rdp|rdp' | xargs -r docker stop; warn 'RDP stopped.'; }
remove_rdp(){ systemctl disable --now xrdp 2>/dev/null || true; apt-get purge -y xrdp 2>/dev/null || true; docker ps -a --format '{{.Names}}' 2>/dev/null | grep -E 'anime-rdp|rdp' | xargs -r docker rm -f; warn 'RDP removed.'; }
menu(){ while true; do clear; echo -e "${C}${B}╔══════════════════════════════════════════════╗${R}"; echo -e "${C}${B}║          ANIME CLOUD — CONTAINER TOOLS       ║${R}"; echo -e "${C}${B}║              ✦ by the mrhacker ✦             ║${R}"; echo -e "${C}${B}╚══════════════════════════════════════════════╝${R}"; echo; echo -e "${G}[1]${R} 🖥️ Install Linux RDP"; echo -e "${G}[2]${R} 🐳 RDP Docker Container"; echo -e "${G}[3]${R} 💻 VS Code Server"; echo -e "${G}[4]${R} 📊 Container / RDP Status"; echo -e "${G}[5]${R} 🛑 Stop RDP"; echo -e "${G}[6]${R} 🗑️ Remove RDP"; echo -e "${RED}[0]${R} ↩ Back"; echo; read -rp 'Container Tools > ' x; case "$x" in 1) install_rdp; pause;; 2) rdp_docker; pause;; 3) vscode; pause;; 4) status; pause;; 5) stop_rdp; pause;; 6) remove_rdp; pause;; 0) exit 0;; *) warn 'Invalid option'; sleep 1;; esac; done; }
[[ $EUID -eq 0 ]] || { echo 'Run as root.'; exit 1; }; menu
